name: Build & deploy Next.js app to Azure Web App

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]

  # Allow manual workflow trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: üå± Checkout to the branch
        uses: actions/checkout@v4

      - name: üçè Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: üìè Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: üîë Create .env file
        run: |
          cat <<'EOF' > .env
          NEXT_PUBLIC_TINA_CLIENT_ID=${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
          TINA_TOKEN=${{ secrets.TINA_TOKEN }}
          NEXT_PUBLIC_TINA_BRANCH=${{ secrets.NEXT_PUBLIC_TINA_BRANCH }}
          NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
          EOF

      - name: ‚öôÔ∏è Install dependencies and build
        run: |
          pnpm install
          pnpm run build

      - name: üìÇ Copy static files
        run: |
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static

      - name: üì¶ Create deployment package
        run: |
          mkdir -p ./deploy-package
          cp -rL ./.next/standalone/* ./deploy-package/
          cp -rL ./.next/standalone/.* ./deploy-package/ 2>/dev/null || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./deploy-package

      - name: üîç Diagnostics
        run: |
          ls -al
          ls ./.next

      # - name: ‚¨ÜÔ∏è Publish Next Application artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Nextjs-site
      #     path: ./site-deploy/Nextjs-site.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: üçè Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # - name: ‚¨áÔ∏è Download artifact from build job
      #   uses: actions/download-artifact@v4.1.8
      #   with:
      #     name: Nextjs-site

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./app

      - name: üóùÔ∏è Azure Login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: AzureChinaCloud

      # Set the build during deployment setting to false. This setting was added in the templates to all azd to work, but breaks deployment via webapps-deploy
      # - name: Azure CLI script
      #   uses: azure/CLI@v2.1.0
      #   with:
      #     inlineScript: |
      #       az cloud set --name AzureChinaCloud
      #       rg=$(az webapp list --query "[?name=='${{ secrets.AZURE_APP_SERVICE_NAME }}'].resourceGroup" --output tsv)
      #       echo Setting SCM_DO_BUILD_DURING_DEPLOYMENT=false on app service ${{ secrets.AZURE_APP_SERVICE_NAME }}
      #       az webapp config appsettings set -n ${{ secrets.AZURE_APP_SERVICE_NAME }} -g $rg --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false -o none
      #       echo Setting --startup-file=\"node server.js\" on app service ${{ secrets.AZURE_APP_SERVICE_NAME }}
      #       az webapp config set --startup-file="node server.js" -n ${{ secrets.AZURE_APP_SERVICE_NAME }} -g $rg -o none
      #       sleep 10

      - name: üöÄ Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.1
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          package: ./app

      # - name: üßπ Cleanup
      #   run: rm -rf app