name: Build & deploy Next.js app to Azure Web App

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]

  # Allow manual workflow trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: üå± Checkout to the branch
        uses: actions/checkout@v4

      - name: üçè Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: üìè Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: üîë Create .env file
        run: |
          cat <<'EOF' > .env
          NEXT_PUBLIC_TINA_CLIENT_ID=${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
          TINA_TOKEN=${{ secrets.TINA_TOKEN }}
          NEXT_PUBLIC_TINA_BRANCH=${{ secrets.NEXT_PUBLIC_TINA_BRANCH }}
          NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
          EOF

      - name: ‚öôÔ∏è Install dependencies and build
        run: |
          pnpm install
          pnpm run build

      - name: Copy static files
        run: |
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static

      - name: üì¶ Create deployment archive with symlinks preserved
        run: |
          cd ./.next/standalone
          tar --no-xattrs -czf ../../deploy.tar.gz .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./deploy.tar.gz
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: üçè Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./

      - name: Move deployment archive
        run: |
          mkdir -p app
          mv deploy.tar.gz app/

      - name: Extract deployment archive
        run: |
          cd app
          tar -xzf deploy.tar.gz

      - name: Delete deployment archive
        run: |
          rm app/deploy.tar.gz
     
      - name: üóùÔ∏è Azure Login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: AzureChinaCloud

      - name: üöÄ Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.1
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          package: ./app